import type { Metadata } from "next";

import "./globals.css";

import { Inter } from "next/font/google";
import { SessionProvider } from "@/components/session-provider";
import { SideMenu } from "@/components/side-menu";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/toast";
import { ToCProvider } from "@/components/toc-provider";
import { TRPCProvider } from "@/components/trpc-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { validateRequest } from "@/lib/auth";

// import { TRPCReactProvider } from "@/trpc/react";

import { TabsStoreProvider } from "./stores/tabs-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> {
  const sessionData = await validateRequest();

  return (
    <html
      suppressHydrationWarning
      className={`${inter.className} h-full`}
      lang="en"
    >
      <body className="flex h-full flex-col">
        <TabsStoreProvider>
          <ThemeProvider
            disableTransitionOnChange
            enableSystem
            attribute="class"
            defaultTheme="dark"
          >
            <TooltipProvider>
              <SessionProvider value={sessionData}>
                <TRPCProvider>
                  <ToCProvider>
                    <main className="flex h-full w-full">{children}</main>
                  </ToCProvider>
                </TRPCProvider>
              </SessionProvider>
            </TooltipProvider>
            <Toaster />
          </ThemeProvider>
        </TabsStoreProvider>
      </body>
    </html>
  );
}
