export enum Genres {
  Adventure = "Adventure",
  Romance = "Romance",
  Mystery = "Mystery",
  Fantasy = "Fantasy",
  ScienceFiction = "Science Fiction",
  Horror = "Horror",
  Thriller = "Thriller",
  HistoricalFiction = "Historical Fiction",
  YoungAdult = "Young Adult",
  ChildrensFiction = "Children's Fiction",
  NonFiction = "Non-Fiction",
  Drama = "Drama",
  Comedy = "Comedy",
  UrbanFantasy = "Urban Fantasy",
  Paranormal = "Paranormal",
  Dystopian = "Dystopian",
  Steampunk = "Steampunk",
  Cyberpunk = "Cyberpunk",
  MagicalRealism = "Magical Realism",
  LiteraryFiction = "Literary Fiction",
}
